# Generated by Django 4.1 on 2023-12-22 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreatePermissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': (('building_insert_2', 'building_insert_2'), ('BuildingSelect', 'BuildingSelect')),
                'managed': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='AppSettings',
            fields=[
                ('gid', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('parameter_name', models.CharField(blank=True, help_text='Nombre del parámetro', max_length=50, null=True, unique=True)),
                ('parameter_value', models.CharField(blank=True, max_length=200, null=True)),
                ('help_en', models.CharField(blank=True, max_length=200, null=True)),
                ('help_es', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'core"."appsettings',
                'managed': True,
            },
        ),
    ]
