#version: '3.2'
#La primera vez al inicializar con docker-compose up, se crean las imágenes y los contenedores
#El servicio db tarda mucho y no se inicia bien la api.
#presionar 


#Después de docker-compose up, SOLO LA PRIMERA VEZ, hay que ejecutar el fichero initdb.sh, 
#del servicio metatierrascol, que está en la misma carpeta que manage.py
#Para Inicializar la base de datos ejecutar:
#
#	docker exec -it metatierrascol_metatierrascol_1 sh -c "./initdb.sh"
#
#Si quieres reiniciar la base de datos, hay que borrar el volumen
#
# 	docker volume rm metatierrascol_metatierrascol-data
services:
  postgis:
    image: postgis/postgis:16-3.4
    restart: "no"
    env_file:
      - .env.dev
    ports:
      - 127.0.0.1:${POSTGRES_FORWARDED_PORT}:5432
    volumes: 
#      - metatierrascol-data:/var/lib/postgresql/data
      - ./postgis-data:/var/lib/postgresql/data
    healthcheck:
        test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "postgres" ]
        interval: 10s
        timeout: 5s
        retries: 5
    networks:
      - postgis

  pgadmin4:
    image: dpage/pgadmin4:8.3
    env_file:
      - .env.dev
    volumes:
      - ./pgadmin4/data:/var/lib/pgadmin
      - ./pgadmin4/servers/servers.json:/pgadmin4/servers.json
    ports:
      - 127.0.0.1:${PGADMIN4_FORWARDED_PORT}:80
    restart: "no"
    depends_on:
      postgis:
        condition: service_healthy
    networks:
      - postgis

#  geoserver:
#    image: docker.osgeo.org/geoserver:2.24.2
#    restart: "no"
#    ports:
#      - 127.0.0.1:${GEOSERVER_FORWARDED_PORT}:8080
#    env_file:
#        - .env
#        - .env.dev
#    volumes:
#      - ./geoserver/geoserver_data:/opt/geoserver_data/:Z
#      - ./geoserver/additional_libs:/opt/additional_libs:Z # by mounting this we can install libs from host on startup
#    networks:
#      - postgis

  metatierrascol:
      restart: "no"
      build: ./metatierrascol
      image: metatierrascol:1
      command: python manage.py runserver 0.0.0.0:8000
      volumes:
        - ./metatierrascol:/usr/src/app
        - ./metatierrascol/media_root:/usr/src/media_root
        - ./metatierrascol/static_root/:/usr/src/static_root
      ports:
        - 127.0.0.1:${METATIERRAS_FORWARDED_PORT}:8000
      env_file:
        - .env.dev
      depends_on:
        postgis:
          condition: service_healthy
      networks:
        - postgis

#volumes:
#  metatierrascol-data:
#    driver: local

networks:
   postgis:
      driver: bridge
