# Generated by Django 4.1 on 2023-12-23 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('departamento', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'codelist"."departamento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EstadoExpediente',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('estado_expediente', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'codelist"."estado_expediente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Lc_prediotipo',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('lc_prediotipo', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'codelist"."lc_prediotipo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('departamento', models.CharField(max_length=100)),
                ('provincia', models.CharField(max_length=100)),
                ('codigo_municipio', models.IntegerField(unique=True)),
                ('nombre_municipio', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'codelist"."municipio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('provincia', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'codelist"."provincia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('sector', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'db_table': 'codelist"."sector',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SnrPersonaTitularTipo',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('snr_persona_titular_tipo', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'db_table': 'codelist"."snr_persona_titular_tipo',
                'managed': False,
            },
        ),
    ]
