# Generated by Django 4.1 on 2023-12-22 17:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('codelist', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Baunit',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateTimeField(auto_now=True)),
                ('fecha_modificacion', models.DateTimeField(null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('nombre', models.TextField(max_length=100)),
                ('numero_predial', models.TextField(max_length=50, null=True, unique=True)),
                ('complemento', models.TextField(help_text='Complemento de la dirección para ayudar a localizar el predio', max_length=200)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creado_por', to=settings.AUTH_USER_MODEL)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='codelist.departamento')),
                ('modificado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modificado_por', to=settings.AUTH_USER_MODEL)),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='codelist.municipio')),
                ('sector_predio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='codelist.sector')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='codelist.lc_prediotipo')),
            ],
            options={
                'db_table': 'baunit"."baunit',
                'managed': True,
            },
        ),
    ]
