# Generated by Django 4.1 on 2023-12-23 07:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Baunit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('nombre', models.TextField(max_length=100)),
                ('numero_predial', models.TextField(max_length=50, null=True, unique=True)),
                ('complemento', models.TextField(help_text='Complemento de la dirección para ayudar a localizar el predio', max_length=200)),
            ],
            options={
                'db_table': 'baunit"."baunit',
                'managed': False,
            },
        ),
    ]
