# Generated by Django 4.1 on 2023-12-18 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppSettings',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('parameter_name', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('parameter_value', models.CharField(blank=True, max_length=200, null=True)),
                ('help_en', models.CharField(blank=True, max_length=200, null=True)),
                ('help_es', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'settings',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('departamento', models.CharField(max_length=100, unique=True)),
                ('provincia', models.CharField(max_length=100, unique=True)),
                ('codigo_municipio', models.IntegerField()),
                ('nombre_municipio', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'municipio',
                'managed': False,
            },
        ),
    ]
