# Generated by Django 4.1 on 2023-12-18 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appcore', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Municipio',
        ),
        migrations.AlterModelTable(
            name='appsettings',
            table='appsettings',
        ),
    ]
