'''
Created on 11 dic 2023

@author: joamona
'''

#[departamento,provincia,codigo_municipio,nombre_municipio],,

from django.db import connection
from pgOperations.pgOperations import PgConnection
from pgOperations.pgOperations import PgConnection, PgOperations, FieldsAndValues

ld=[
['Casanare'],
['Cundinamarca'],
['Tolima'],
['Meta'],
['Antioquia'],
['Boyacá'],
['Vaupes'],
['Santander'],
['Córdoba'],
['Guaviare'],
['Choco'],
['Archipiélago de San Andrés'],
['Guainia'],
['Sucre'],
['Arauca'],
['Nariño'],
['Amazonas'],
['Bogotá DC'],
['Magdalena'],
['Norte de Santander'],
['Caqueta'],
['Risaralda'],
['Vichada'],
['La Guajira'],
['Cesar'],
['Quindio'],
['Cauca'],
['Putumayo'],
['Caldas'],
['Valle del Cauca'],
['Huila'],
['Bolívar'],
['Atlántico']
]

lp=[
['Sugamuxi'],
['García Rovira'],
['Río Negro'],
['Magdalena Medio Bilivariense'],
['San Jorge'],
['Gutiérrez'],
['Noroccidental'],
['Sumapaz'],
['Vélez'],
['Occidental'],
['Magdalena Centro'],
['Alto Magdalena'],
['Almeidas'],
['Mojana Volivariense'],
['Morroso Uillo'],
['Costa'],
['Occidente'],
['Dos – Vertiente Occidental'],
['Sur'],
['Medina'],
['Guaviare'],
['Guainia'],
['Bajo Sinú'],
['Uraba'],
['Norte'],
['Capital'],
['Magdalen a medio'],
['Soacha'],
['Bogotá'],
['Sabanas'],
['Valderrama'],
['Amazonas'],
['Sábanas'],
['Gualiva'],
['Centro'],
['Darien'],
['Vichada'],
['Ariari'],
['San Juan'],
['Nordeste'],
['Comunera'],
['Suroriente'],
['Uno – Vertiente Oriental'],
['Central'],
['Montes de María'],
['Guanenta'],
['Márquez'],
['Loba'],
['Alto Occidente'],
['Bajo Magdalena'],
['Pacifico Norte'],
['Sur Occidente'],
['Oriental'],
['Sur Oriente'],
['Casanare'],
['Pacífico Sur'],
['Suroeste'],
['Tundama'],
['Mojana'],
['Valle'],
['Oriente'],
['Río Meta'],
['Ricaurte'],
['Vaupes'],
['Ubate'],
['Tequendama'],
['Depresión Momposina'],
['Tres – Vertiente del Pacífico'],
['Guavio'],
['Soto'],
['Sabana Centro'],
['Alto Sinú'],
['Mares'],
['Acostanera'],
['Santa Marta'],
['Valle del Aburra'],
['Archipiélago de San Andrés'],
['Lengupa'],
['Centro Oriente'],
['Río'],
['Sabana Occidente'],
['Bajo Cauca'],
['Bajo Occidente'],
['Dique Bilivarense'],
['Centro Occidente'],
['Atrato'],
['Arauca'],
['Sinú Medio'],
['Ibague'],
['Alto Oriente'],
['Nevados'],
['Piedemonte'],
['Caqueta'],
['La Libertad'],
['Cordilléranos'],
['Neira'],
['Putumayo'],
['Fría']
]

lm=[
    ['Amazonas','Amazonas',91263,'El Encanto'],
    ['Amazonas','Amazonas',91405,'La Chorrera'],
    ['Amazonas','Amazonas',91407,'La Pedrera'],
    ['Amazonas','Amazonas',91430,'La Victoria'],
    ['Amazonas','Amazonas',91001,'Leticia'],
    ['Amazonas','Amazonas',91460,'Miriti - Paraná'],
    ['Amazonas','Amazonas',91530,'Puerto Alegria'],
    ['Amazonas','Amazonas',91536,'Puerto Arica'],
    ['Amazonas','Amazonas',91540,'Puerto Nariño'],
    ['Amazonas','Amazonas',91669,'Puerto Santander'],
    ['Amazonas','Amazonas',91798,'Tarapacá'],
    ['Antioquia','Bajo Cauca',5120,'Cáceres'],
    ['Antioquia','Bajo Cauca',5154,'Caucasia'],
    ['Antioquia','Bajo Cauca',5250,'El Bagre'],
    ['Antioquia','Bajo Cauca',5495,'Nechí'],
    ['Antioquia','Bajo Cauca',5790,'Tarazá'],
    ['Antioquia','Bajo Cauca',5895,'Zaragoza'],
    ['Antioquia','Magdalen a medio',5142,'Caracolí'],
    ['Antioquia','Magdalen a medio',5425,'Maceo'],
    ['Antioquia','Magdalen a medio',5579,'Puerto Berrio'],
    ['Antioquia','Magdalen a medio',5585,'Puerto Nare'],
    ['Antioquia','Magdalen a medio',5591,'Puerto Triunfo'],
    ['Antioquia','Magdalen a medio',5893,'Yondó'],
    ['Antioquia','Nordeste',5031,'Amalfi'],
    ['Antioquia','Nordeste',5040,'Anorí'],
    ['Antioquia','Nordeste',5190,'Cisneros'],
    ['Antioquia','Nordeste',5604,'Remedios'],
    ['Antioquia','Nordeste',5670,'San Roque'],
    ['Antioquia','Nordeste',5690,'Santo Domingo'],
    ['Antioquia','Nordeste',5736,'Segovia'],
    ['Antioquia','Nordeste',5858,'Vegachí'],
    ['Antioquia','Nordeste',5885,'Yalí'],
    ['Antioquia','Nordeste',5890,'Yolombó'],
    ['Antioquia','Norte',5038,'Angostura'],
    ['Antioquia','Norte',5086,'Belmira'],
    ['Antioquia','Norte',5107,'Briceño'],
    ['Antioquia','Norte',5134,'Campamento'],
    ['Antioquia','Norte',5150,'Carolina'],
    ['Antioquia','Norte',5237,'Don Matias'],
    ['Antioquia','Norte',5264,'Entrerrios'],
    ['Antioquia','Norte',5310,'Gómez Plata'],
    ['Antioquia','Norte',5315,'Guadalupe'],
    ['Antioquia','Norte',5361,'Ituango'],
    ['Antioquia','Norte',5647,'San Andrés'],
    ['Antioquia','Norte',5658,'San José De La Montaña'],
    ['Antioquia','Norte',5664,'San Pedro'],
    ['Antioquia','Norte',5686,'Santa Rosa De Osos'],
    ['Antioquia','Norte',5819,'Toledo'],
    ['Antioquia','Norte',5854,'Valdivia'],
    ['Antioquia','Norte',5887,'Yarumal'],
    ['Antioquia','Occidente',5004,'Abriaquí'],
    ['Antioquia','Occidente',5044,'Anza'],
    ['Antioquia','Occidente',5059,'Armenia'],
    ['Antioquia','Occidente',5113,'Buriticá'],
    ['Antioquia','Occidente',5138,'Cañasgordas'],
    ['Antioquia','Occidente',5234,'Dabeiba'],
    ['Antioquia','Occidente',5240,'Ebéjico'],
    ['Antioquia','Occidente',5284,'Frontino'],
    ['Antioquia','Occidente',5306,'Giraldo'],
    ['Antioquia','Occidente',5347,'Heliconia'],
    ['Antioquia','Occidente',5411,'Liborina'],
    ['Antioquia','Occidente',5501,'Olaya'],
    ['Antioquia','Occidente',5543,'Peque'],
    ['Antioquia','Occidente',5628,'Sabanalarga'],
    ['Antioquia','Occidente',5656,'San Jerónimo'],
    ['Antioquia','Occidente',5042,'Santafé De Antioquia'],
    ['Antioquia','Occidente',5761,'Sopetran'],
    ['Antioquia','Occidente',5842,'Uramita'],
    ['Antioquia','Oriente',5002,'Abejorral'],
    ['Antioquia','Oriente',5021,'Alejandría'],
    ['Antioquia','Oriente',5055,'Argelia'],
    ['Antioquia','Oriente',5148,'Carmen De Viboral'],
    ['Antioquia','Oriente',5197,'Cocorná'],
    ['Antioquia','Oriente',5206,'Concepción'],
    ['Antioquia','Oriente',5313,'Granada'],
    ['Antioquia','Oriente',5318,'Guarne'],
    ['Antioquia','Oriente',5321,'Guatape'],
    ['Antioquia','Oriente',5376,'La Ceja'],
    ['Antioquia','Oriente',5400,'La Unión'],
    ['Antioquia','Oriente',5440,'Marinilla'],
    ['Antioquia','Oriente',5483,'Nariño'],
    ['Antioquia','Oriente',5541,'Peñol'],
    ['Antioquia','Oriente',5607,'Retiro'],
    ['Antioquia','Oriente',5615,'Rionegro'],
    ['Antioquia','Oriente',5649,'San Carlos'],
    ['Antioquia','Oriente',5652,'San Francisco'],
    ['Antioquia','Oriente',5660,'San Luis'],
    ['Antioquia','Oriente',5667,'San Rafael'],
    ['Antioquia','Oriente',5674,'San Vicente'],
    ['Antioquia','Oriente',5697,'Santuario'],
    ['Antioquia','Oriente',5756,'Sonson'],
    ['Antioquia','Suroeste',5030,'Amaga'],
    ['Antioquia','Suroeste',5034,'Andes'],
    ['Antioquia','Suroeste',5036,'Angelopolis'],
    ['Antioquia','Suroeste',5091,'Betania'],
    ['Antioquia','Suroeste',5093,'Betulia'],
    ['Antioquia','Suroeste',5125,'Caicedo'],
    ['Antioquia','Suroeste',5145,'Caramanta'],
    ['Antioquia','Suroeste',5101,'Ciudad Bolívar'],
    ['Antioquia','Suroeste',5209,'Concordia'],
    ['Antioquia','Suroeste',5282,'Fredonia'],
    ['Antioquia','Suroeste',5353,'Hispania'],
    ['Antioquia','Suroeste',5364,'Jardín'],
    ['Antioquia','Suroeste',5368,'Jericó'],
    ['Antioquia','Suroeste',5390,'La Pintada'],
    ['Antioquia','Suroeste',5467,'Montebello'],
    ['Antioquia','Suroeste',5576,'Pueblorrico'],
    ['Antioquia','Suroeste',5642,'Salgar'],
    ['Antioquia','Suroeste',5679,'Santa Barbara'],
    ['Antioquia','Suroeste',5789,'Támesis'],
    ['Antioquia','Suroeste',5792,'Tarso'],
    ['Antioquia','Suroeste',5809,'Titiribí'],
    ['Antioquia','Suroeste',5847,'Urrao'],
    ['Antioquia','Suroeste',5856,'Valparaiso'],
    ['Antioquia','Suroeste',5861,'Venecia'],
    ['Antioquia','Uraba',5045,'Apartadó'],
    ['Antioquia','Uraba',5051,'Arboletes'],
    ['Antioquia','Uraba',5147,'Carepa'],
    ['Antioquia','Uraba',5172,'Chigorodó'],
    ['Antioquia','Uraba',5475,'Murindó'],
    ['Antioquia','Uraba',5480,'Mutata'],
    ['Antioquia','Uraba',5490,'Necoclí'],
    ['Antioquia','Uraba',5659,'San Juan De Uraba'],
    ['Antioquia','Uraba',5665,'San Pedro De Uraba'],
    ['Antioquia','Uraba',5837,'Turbo'],
    ['Antioquia','Uraba',5873,'Vigía Del Fuerte'],
    ['Antioquia','Valle del Aburra',5079,'Barbosa'],
    ['Antioquia','Valle del Aburra',5088,'Bello'],
    ['Antioquia','Valle del Aburra',5129,'Caldas'],
    ['Antioquia','Valle del Aburra',5212,'Copacabana'],
    ['Antioquia','Valle del Aburra',5266,'Envigado'],
    ['Antioquia','Valle del Aburra',5308,'Girardota'],
    ['Antioquia','Valle del Aburra',5360,'Itagui'],
    ['Antioquia','Valle del Aburra',5380,'La Estrella'],
    ['Antioquia','Valle del Aburra',5001,'Medellín'],
    ['Antioquia','Valle del Aburra',5631,'Sabaneta'],
    ['Arauca','Arauca',81001,'Arauca'],
    ['Arauca','Arauca',81065,'Arauquita'],
    ['Arauca','Arauca',81220,'Cravo Norte'],
    ['Arauca','Arauca',81300,'Fortul'],
    ['Arauca','Arauca',81591,'Puerto Rondón'],
    ['Arauca','Arauca',81736,'Saravena'],
    ['Arauca','Arauca',81794,'Tame'],
    ['Archipiélago de San Andrés','Archipiélago de San Andrés',88564,'Providencia Y Santa Catalina'],
    ['Archipiélago de San Andrés','Archipiélago de San Andrés',88001,'San Andres'],
    ['Atlántico','Norte',8001,'Barranquilla'],
    ['Atlántico','Norte',8296,'Galapa'],
    ['Atlántico','Norte',8433,'Malambo'],
    ['Atlántico','Norte',8573,'Puerto Colombia'],
    ['Atlántico','Norte',8758,'Soledad'],
    ['Atlántico','Sur',8137,'Campo De La Cruz'],
    ['Atlántico','Sur',8141,'Candelaria'],
    ['Atlántico','Sur',8421,'Luruaco'],
    ['Atlántico','Sur',8436,'Manati'],
    ['Atlántico','Sur',8606,'Repelon'],
    ['Atlántico','Sur',8675,'Santa Lucia'],
    ['Atlántico','Sur',8770,'Suan'],
    ['Atlántico','Centro Oriente',8078,'Baranoa'],
    ['Atlántico','Centro Oriente',8520,'Palmar De Varela'],
    ['Atlántico','Centro Oriente',8558,'Polonuevo'],
    ['Atlántico','Centro Oriente',8560,'Ponedera'],
    ['Atlántico','Centro Oriente',8634,'Sabanagrande'],
    ['Atlántico','Centro Oriente',8638,'Sabanalarga'],
    ['Atlántico','Centro Oriente',8685,'Santo Tomas'],
    ['Atlántico','Occidental',8372,'Juan De Acosta'],
    ['Atlántico','Occidental',8549,'Piojó'],
    ['Atlántico','Occidental',8832,'Tubara'],
    ['Atlántico','Occidental',8849,'Usiacuri'],
    ['Bogotá DC','Bogotá',11001,'Bogota D.C.'],
    ['Bolívar','Depresión Momposina',13188,'Cicuco'],
    ['Bolívar','Depresión Momposina',13300,'Hatillo De Loba'],
    ['Bolívar','Depresión Momposina',13440,'Margarita'],
    ['Bolívar','Depresión Momposina',13468,'Mompós'],
    ['Bolívar','Depresión Momposina',13650,'San Fernando'],
    ['Bolívar','Depresión Momposina',13780,'Talaigua Nuevo'],
    ['Bolívar','Dique Bilivarense',13052,'Arjona'],
    ['Bolívar','Dique Bilivarense',13062,'Arroyohondo'],
    ['Bolívar','Dique Bilivarense',13140,'Calamar'],
    ['Bolívar','Dique Bilivarense',13001,'Cartagena'],
    ['Bolívar','Dique Bilivarense',13222,'Clemencia'],
    ['Bolívar','Dique Bilivarense',13433,'Mahates'],
    ['Bolívar','Dique Bilivarense',13620,'San Cristobal'],
    ['Bolívar','Dique Bilivarense',13647,'San Estanislao'],
    ['Bolívar','Dique Bilivarense',13673,'Santa Catalina'],
    ['Bolívar','Dique Bilivarense',13683,'Santa Rosa De Lima'],
    ['Bolívar','Dique Bilivarense',13760,'Soplaviento'],
    ['Bolívar','Dique Bilivarense',13836,'Turbaco'],
    ['Bolívar','Dique Bilivarense',13838,'Turbana'],
    ['Bolívar','Dique Bilivarense',13873,'Villanueva'],
    ['Bolívar','Loba',13030,'Altos Del Rosario'],
    ['Bolívar','Loba',13074,'Barranco De Loba'],
    ['Bolívar','Loba',13268,'El Peñon'],
    ['Bolívar','Loba',13580,'Regidor'],
    ['Bolívar','Loba',13600,'Río Viejo'],
    ['Bolívar','Loba',13667,'San Martin De Loba'],
    ['Bolívar','Magdalena Medio Bilivariense',13042,'Arenal'],
    ['Bolívar','Magdalena Medio Bilivariense',13160,'Cantagallo'],
    ['Bolívar','Magdalena Medio Bilivariense',13473,'Morales'],
    ['Bolívar','Magdalena Medio Bilivariense',13670,'San Pablo'],
    ['Bolívar','Magdalena Medio Bilivariense',13688,'Santa Rosa Del Sur'],
    ['Bolívar','Magdalena Medio Bilivariense',13744,'Simití'],
    ['Bolívar','Mojana Volivariense',13006,'Achí'],
    ['Bolívar','Mojana Volivariense',13430,'Magangué'],
    ['Bolívar','Mojana Volivariense',13458,'Montecristo'],
    ['Bolívar','Mojana Volivariense',13549,'Pinillos'],
    ['Bolívar','Mojana Volivariense',13655,'San Jacinto Del Cauca'],
    ['Bolívar','Mojana Volivariense',13810,'Tiquisio'],
    ['Bolívar','Montes de María',13244,'Carmen De Bolívar'],
    ['Bolívar','Montes de María',13212,'Córdoba'],
    ['Bolívar','Montes de María',13248,'El Guamo'],
    ['Bolívar','Montes de María',13442,'María La Baja'],
    ['Bolívar','Montes de María',13654,'San Jacinto'],
    ['Bolívar','Montes de María',13657,'San Juan Nepomuceno'],
    ['Bolívar','Montes de María',13894,'Zambrano'],
    ['Boyacá','Centro',15232,'Chíquiza'],
    ['Boyacá','Centro',15187,'Chivatá'],
    ['Boyacá','Centro',15204,'Cómbita'],
    ['Boyacá','Centro',15224,'Cucaita'],
    ['Boyacá','Centro',15476,'Motavita'],
    ['Boyacá','Centro',15500,'Oicatá'],
    ['Boyacá','Centro',15646,'Samacá'],
    ['Boyacá','Centro',15740,'Siachoque'],
    ['Boyacá','Centro',15762,'Sora'],
    ['Boyacá','Centro',15764,'Soracá'],
    ['Boyacá','Centro',15763,'Sotaquirá'],
    ['Boyacá','Centro',15814,'Toca'],
    ['Boyacá','Centro',15001,'Tunja'],
    ['Boyacá','Centro',15837,'Tuta'],
    ['Boyacá','Centro',15861,'Ventaquemada'],
    ['Boyacá','Gutiérrez',15180,'Chiscas'],
    ['Boyacá','Gutiérrez',15223,'Cubará'],
    ['Boyacá','Gutiérrez',15244,'El Cocuy'],
    ['Boyacá','Gutiérrez',15248,'El Espino'],
    ['Boyacá','Gutiérrez',15317,'Guacamayas'],
    ['Boyacá','Gutiérrez',15332,'Güicán'],
    ['Boyacá','Gutiérrez',15522,'Panqueba'],
    ['Boyacá','La Libertad',15377,'Labranzagrande'],
    ['Boyacá','La Libertad',15518,'Pajarito'],
    ['Boyacá','La Libertad',15533,'Paya'],
    ['Boyacá','La Libertad',15550,'Pisba'],
    ['Boyacá','Lengupa',15090,'Berbeo'],
    ['Boyacá','Lengupa',15135,'Campohermoso'],
    ['Boyacá','Lengupa',15455,'Miraflores'],
    ['Boyacá','Lengupa',15514,'Páez'],
    ['Boyacá','Lengupa',15660,'San Eduardo'],
    ['Boyacá','Lengupa',15897,'Zetaquira'],
    ['Boyacá','Márquez',15104,'Boyacá'],
    ['Boyacá','Márquez',15189,'Ciénega'],
    ['Boyacá','Márquez',15367,'Jenesano'],
    ['Boyacá','Márquez',15494,'Nuevo Colón'],
    ['Boyacá','Márquez',15599,'Ramiriquí'],
    ['Boyacá','Márquez',15621,'Rondón'],
    ['Boyacá','Márquez',15804,'Tibaná'],
    ['Boyacá','Márquez',15835,'Turmequé'],
    ['Boyacá','Márquez',15842,'Umbita'],
    ['Boyacá','Márquez',15879,'Viracachá'],
    ['Boyacá','Neira',15172,'Chinavita'],
    ['Boyacá','Neira',15299,'Garagoa'],
    ['Boyacá','Neira',15425,'Macanal'],
    ['Boyacá','Neira',15511,'Pachavita'],
    ['Boyacá','Neira',15667,'San Luis De Gaceno'],
    ['Boyacá','Neira',15690,'Santa María'],
    ['Boyacá','Norte',15097,'Boavita'],
    ['Boyacá','Norte',15218,'Covarachía'],
    ['Boyacá','Norte',15403,'La Uvita'],
    ['Boyacá','Norte',15673,'San Mateo'],
    ['Boyacá','Norte',15720,'Sativanorte'],
    ['Boyacá','Norte',15723,'Sativasur'],
    ['Boyacá','Norte',15753,'Soatá'],
    ['Boyacá','Norte',15774,'Susacón'],
    ['Boyacá','Norte',15810,'Tipacoque'],
    ['Boyacá','Occidente',15106,'Briceño'],
    ['Boyacá','Occidente',15109,'Buenavista'],
    ['Boyacá','Occidente',15131,'Caldas'],
    ['Boyacá','Occidente',15176,'Chiquinquirá'],
    ['Boyacá','Occidente',15212,'Coper'],
    ['Boyacá','Occidente',15401,'La Victoria'],
    ['Boyacá','Occidente',15442,'Maripí'],
    ['Boyacá','Occidente',15480,'Muzo'],
    ['Boyacá','Occidente',15507,'Otanche'],
    ['Boyacá','Occidente',15531,'Pauna'],
    ['Boyacá','Occidente',15572,'Puerto Boyaca'],
    ['Boyacá','Occidente',15580,'Quípama'],
    ['Boyacá','Occidente',15632,'Saboyá'],
    ['Boyacá','Occidente',15676,'San Miguel De Sema'],
    ['Boyacá','Occidente',15681,'San Pablo Borbur'],
    ['Boyacá','Occidente',15832,'Tununguá'],
    ['Boyacá','Oriente',15022,'Almeida'],
    ['Boyacá','Oriente',15236,'Chivor'],
    ['Boyacá','Oriente',15322,'Guateque'],
    ['Boyacá','Oriente',15325,'Guayatá'],
    ['Boyacá','Oriente',15380,'La Capilla'],
    ['Boyacá','Oriente',15761,'Somondoco'],
    ['Boyacá','Oriente',15778,'Sutatenza'],
    ['Boyacá','Oriente',15798,'Tenza'],
    ['Boyacá','Ricaurte',15051,'Arcabuco'],
    ['Boyacá','Ricaurte',15185,'Chitaraque'],
    ['Boyacá','Ricaurte',15293,'Gachantivá'],
    ['Boyacá','Ricaurte',15469,'Moniquirá'],
    ['Boyacá','Ricaurte',15600,'Ráquira'],
    ['Boyacá','Ricaurte',15638,'Sáchica'],
    ['Boyacá','Ricaurte',15664,'San José De Pare'],
    ['Boyacá','Ricaurte',15696,'Santa Sofía'],
    ['Boyacá','Ricaurte',15686,'Santana'],
    ['Boyacá','Ricaurte',15776,'Sutamarchán'],
    ['Boyacá','Ricaurte',15808,'Tinjacá'],
    ['Boyacá','Ricaurte',15816,'Togüí'],
    ['Boyacá','Ricaurte',15407,'Villa De Leyva'],
    ['Boyacá','Sugamuxi',15047,'Aquitania'],
    ['Boyacá','Sugamuxi',15226,'Cuítiva'],
    ['Boyacá','Sugamuxi',15272,'Firavitoba'],
    ['Boyacá','Sugamuxi',15296,'Gameza'],
    ['Boyacá','Sugamuxi',15362,'Iza'],
    ['Boyacá','Sugamuxi',15464,'Mongua'],
    ['Boyacá','Sugamuxi',15466,'Monguí'],
    ['Boyacá','Sugamuxi',15491,'Nobsa'],
    ['Boyacá','Sugamuxi',15542,'Pesca'],
    ['Boyacá','Sugamuxi',15759,'Sogamoso'],
    ['Boyacá','Sugamuxi',15806,'Tibasosa'],
    ['Boyacá','Sugamuxi',15820,'Tópaga'],
    ['Boyacá','Sugamuxi',15822,'Tota'],
    ['Boyacá','Tundama',15087,'Belén'],
    ['Boyacá','Tundama',15114,'Busbanzá'],
    ['Boyacá','Tundama',15162,'Cerinza'],
    ['Boyacá','Tundama',15215,'Corrales'],
    ['Boyacá','Tundama',15238,'Duitama'],
    ['Boyacá','Tundama',15276,'Floresta'],
    ['Boyacá','Tundama',15516,'Paipa'],
    ['Boyacá','Tundama',15693,'San Rosa Viterbo'],
    ['Boyacá','Tundama',15839,'Tutazá'],
    ['Boyacá','Valderrama',15092,'Betéitiva'],
    ['Boyacá','Valderrama',15183,'Chita'],
    ['Boyacá','Valderrama',15368,'Jericó'],
    ['Boyacá','Valderrama',15537,'Paz De Río'],
    ['Boyacá','Valderrama',15757,'Socha'],
    ['Boyacá','Valderrama',15755,'Socotá'],
    ['Boyacá','Valderrama',15790,'Tasco'],
    ['Caldas','Alto Occidente',17272,'Filadelfia'],
    ['Caldas','Alto Occidente',17388,'La Merced'],
    ['Caldas','Alto Occidente',17442,'Marmato'],
    ['Caldas','Alto Occidente',17614,'Riosucio'],
    ['Caldas','Alto Occidente',17777,'Supía'],
    ['Caldas','Alto Oriente',17433,'Manzanares'],
    ['Caldas','Alto Oriente',17444,'Marquetalia'],
    ['Caldas','Alto Oriente',17446,'Marulanda'],
    ['Caldas','Alto Oriente',17541,'Pensilvania'],
    ['Caldas','Bajo Occidente',17042,'Anserma'],
    ['Caldas','Bajo Occidente',17088,'Belalcázar'],
    ['Caldas','Bajo Occidente',17616,'Risaralda'],
    ['Caldas','Bajo Occidente',17665,'San José'],
    ['Caldas','Bajo Occidente',17877,'Viterbo'],
    ['Caldas','Centro',17174,'Chinchina'],
    ['Caldas','Centro',17001,'Manizales'],
    ['Caldas','Centro',17486,'Neira'],
    ['Caldas','Centro',17524,'Palestina'],
    ['Caldas','Centro',17873,'Villamaria'],
    ['Caldas','Norte',17013,'Aguadas'],
    ['Caldas','Norte',17050,'Aranzazu'],
    ['Caldas','Norte',17513,'Pácora'],
    ['Caldas','Norte',17653,'Salamina'],
    ['Caldas','Oriente',17380,'La Dorada'],
    ['Caldas','Oriente',17495,'Norcasia'],
    ['Caldas','Oriente',17662,'Samaná'],
    ['Caldas','Oriente',17867,'Victoria'],
    ['Caqueta','Caqueta',18029,'Albania'],
    ['Caqueta','Caqueta',18094,'Belén De Los Andaquies'],
    ['Caqueta','Caqueta',18150,'Cartagena Del Chairá'],
    ['Caqueta','Caqueta',18205,'Currillo'],
    ['Caqueta','Caqueta',18247,'El Doncello'],
    ['Caqueta','Caqueta',18256,'El Paujil'],
    ['Caqueta','Caqueta',18001,'Florencia'],
    ['Caqueta','Caqueta',18410,'La Montañita'],
    ['Caqueta','Caqueta',18460,'Milan'],
    ['Caqueta','Caqueta',18479,'Morelia'],
    ['Caqueta','Caqueta',18592,'Puerto Rico'],
    ['Caqueta','Caqueta',18610,'San Jose Del Fragua'],
    ['Caqueta','Caqueta',18753,'San Vicente Del Caguán'],
    ['Caqueta','Caqueta',18756,'Solano'],
    ['Caqueta','Caqueta',18785,'Solita'],
    ['Caqueta','Caqueta',18860,'Valparaiso'],
    ['Casanare','Casanare',85010,'Aguazul'],
    ['Casanare','Casanare',85015,'Chameza'],
    ['Casanare','Casanare',85125,'Hato Corozal'],
    ['Casanare','Casanare',85136,'La Salina'],
    ['Casanare','Casanare',85139,'Maní'],
    ['Casanare','Casanare',85162,'Monterrey'],
    ['Casanare','Casanare',85225,'Nunchía'],
    ['Casanare','Casanare',85230,'Orocué'],
    ['Casanare','Casanare',85250,'Paz De Ariporo'],
    ['Casanare','Casanare',85263,'Pore'],
    ['Casanare','Casanare',85279,'Recetor'],
    ['Casanare','Casanare',85300,'Sabanalarga'],
    ['Casanare','Casanare',85315,'Sácama'],
    ['Casanare','Casanare',85325,'San Luis De Palenque'],
    ['Casanare','Casanare',85400,'Támara'],
    ['Casanare','Casanare',85410,'Tauramena'],
    ['Casanare','Casanare',85430,'Trinidad'],
    ['Casanare','Casanare',85440,'Villanueva'],
    ['Casanare','Casanare',85001,'Yopal'],
    ['Cauca','Centro',19130,'Cajibío'],
    ['Cauca','Centro',19256,'El Tambo'],
    ['Cauca','Centro',19392,'La Sierra'],
    ['Cauca','Centro',19473,'Morales'],
    ['Cauca','Centro',19548,'Piendamo'],
    ['Cauca','Centro',19001,'Popayán'],
    ['Cauca','Centro',19622,'Rosas'],
    ['Cauca','Centro',19760,'Sotara'],
    ['Cauca','Centro',19807,'Timbio'],
    ['Cauca','Norte',19110,'Buenos Aires'],
    ['Cauca','Norte',19142,'Caloto'],
    ['Cauca','Norte',19212,'Corinto'],
    ['Cauca','Norte',19455,'Miranda'],
    ['Cauca','Norte',19513,'Padilla'],
    ['Cauca','Norte',19573,'Puerto Tejada'],
    ['Cauca','Norte',19698,'Santander De Quilichao'],
    ['Cauca','Norte',19780,'Suarez'],
    ['Cauca','Norte',19845,'Villa Rica'],
    ['Cauca','Occidente',19318,'Guapi'],
    ['Cauca','Occidente',19418,'Lopez'],
    ['Cauca','Occidente',19809,'Timbiqui'],
    ['Cauca','Oriente',19137,'Caldono'],
    ['Cauca','Oriente',19355,'Inzá'],
    ['Cauca','Oriente',19364,'Jambalo'],
    ['Cauca','Oriente',19517,'Paez'],
    ['Cauca','Oriente',19585,'Purace'],
    ['Cauca','Oriente',19743,'Silvia'],
    ['Cauca','Oriente',19821,'Toribio'],
    ['Cauca','Oriente',19824,'Totoro'],
    ['Cauca','Sur',19022,'Almaguer'],
    ['Cauca','Sur',19050,'Argelia'],
    ['Cauca','Sur',19075,'Balboa'],
    ['Cauca','Sur',19100,'Bolívar'],
    ['Cauca','Sur',19290,'Florencia'],
    ['Cauca','Sur',19397,'La Vega'],
    ['Cauca','Sur',19450,'Mercaderes'],
    ['Cauca','Sur',19532,'Patia'],
    ['Cauca','Sur',19533,'Piamonte'],
    ['Cauca','Sur',19693,'San Sebastian'],
    ['Cauca','Sur',19701,'Santa Rosa'],
    ['Cauca','Sur',19785,'Sucre'],
    ['Cesar','Central',20045,'Becerril'],
    ['Cesar','Central',20175,'Chimichagua'],
    ['Cesar','Central',20178,'Chiriguana'],
    ['Cesar','Central',20228,'Curumaní'],
    ['Cesar','Central',20400,'La Jagua De Ibirico'],
    ['Cesar','Central',20517,'Pailitas'],
    ['Cesar','Central',20787,'Tamalameque'],
    ['Cesar','Noroccidental',20032,'Astrea'],
    ['Cesar','Noroccidental',20060,'Bosconia'],
    ['Cesar','Noroccidental',20238,'El Copey'],
    ['Cesar','Noroccidental',20250,'El Paso'],
    ['Cesar','Norte',20013,'Agustín Codazzi'],
    ['Cesar','Norte',20621,'La Paz'],
    ['Cesar','Norte',20443,'Manaure'],
    ['Cesar','Norte',20570,'Pueblo Bello'],
    ['Cesar','Norte',20750,'San Diego'],
    ['Cesar','Norte',20001,'Valledupar'],
    ['Cesar','Sur',20011,'Aguachica'],
    ['Cesar','Sur',20295,'Gamarra'],
    ['Cesar','Sur',20310,'González'],
    ['Cesar','Sur',20383,'La Gloria'],
    ['Cesar','Sur',20550,'Pelaya'],
    ['Cesar','Sur',20614,'Río De Oro'],
    ['Cesar','Sur',20710,'San Alberto'],
    ['Cesar','Sur',20770,'San Martín'],
    ['Choco','Atrato',27050,'Atrato'],
    ['Choco','Atrato',27073,'Bagadó'],
    ['Choco','Atrato',27099,'Bojaya'],
    ['Choco','Atrato',27245,'El Carmen De Atrato'],
    ['Choco','Atrato',27413,'Lloró'],
    ['Choco','Atrato',27425,'Medio Atrato'],
    ['Choco','Atrato',27001,'Quibdó'],
    ['Choco','Atrato',27600,'Rio Quito'],
    ['Choco','Darien',27006,'Acandí'],
    ['Choco','Darien',27086,'Belén De Bajira'],
    ['Choco','Darien',27150,'Carmén Del Darién'],
    ['Choco','Darien',27615,'Riosucio'],
    ['Choco','Darien',27800,'Unguía'],
    ['Choco','Pacifico Norte',27075,'Bahía Solano'],
    ['Choco','Pacifico Norte',27372,'Juradó'],
    ['Choco','Pacifico Norte',27495,'Nuquí'],
    ['Choco','Pacífico Sur',27025,'Alto Baudó'],
    ['Choco','Pacífico Sur',27077,'Bajo Baudó'],
    ['Choco','Pacífico Sur',27250,'El Litoral Del San Juan'],
    ['Choco','Pacífico Sur',27430,'Medio Baudó'],
    ['Choco','San Juan',27135,'Canton De San Pablo'],
    ['Choco','San Juan',27160,'Certegui'],
    ['Choco','San Juan',27205,'Condoto'],
    ['Choco','San Juan',27361,'Itsmina'],
    ['Choco','San Juan',27450,'Medio San Juan'],
    ['Choco','San Juan',27491,'Nóvita'],
    ['Choco','San Juan',27580,'Río Frío'],
    ['Choco','San Juan',27660,'San José Del Palmar'],
    ['Choco','San Juan',27745,'Sipí'],
    ['Choco','San Juan',27787,'Tadó'],
    ['Choco','San Juan',27810,'Union Panamericana'],
    ['Córdoba','Alto Sinú',23807,'Tierralta'],
    ['Córdoba','Alto Sinú',23855,'Valencia'],
    ['Córdoba','Bajo Sinú',23168,'Chimá'],
    ['Córdoba','Bajo Sinú',23300,'Cotorra'],
    ['Córdoba','Bajo Sinú',23417,'Lorica'],
    ['Córdoba','Bajo Sinú',23464,'Momil'],
    ['Córdoba','Bajo Sinú',23586,'Purísima'],
    ['Córdoba','Centro',23001,'Montería'],
    ['Córdoba','Acostanera',23090,'Canalete'],
    ['Córdoba','Acostanera',23419,'Los Córdobas'],
    ['Córdoba','Acostanera',23500,'Moñitos'],
    ['Córdoba','Acostanera',23574,'Puerto Escondido'],
    ['Córdoba','Acostanera',23672,'San Antero'],
    ['Córdoba','Acostanera',23675,'San Bernardo Del Viento'],
    ['Córdoba','Sábanas',23182,'Chinú'],
    ['Córdoba','Sábanas',23660,'Sahagún'],
    ['Córdoba','Sábanas',23670,'San Andrés Sotavento'],
    ['Córdoba','San Jorge',23068,'Ayapel'],
    ['Córdoba','San Jorge',23079,'Buenavista'],
    ['Córdoba','San Jorge',23350,'La Apartada'],
    ['Córdoba','San Jorge',23466,'Montelíbano'],
    ['Córdoba','San Jorge',23555,'Planeta Rica'],
    ['Córdoba','San Jorge',23570,'Pueblo Nuevo'],
    ['Córdoba','San Jorge',23580,'Puerto Libertador'],
    ['Córdoba','Sinú Medio',23162,'Cereté'],
    ['Córdoba','Sinú Medio',23189,'Ciénaga De Oro'],
    ['Córdoba','Sinú Medio',23678,'San Carlos'],
    ['Córdoba','Sinú Medio',23686,'San Pelayo'],
    ['Cundinamarca','Almeidas',25183,'Chocontá'],
    ['Cundinamarca','Almeidas',25426,'Macheta'],
    ['Cundinamarca','Almeidas',25436,'Manta'],
    ['Cundinamarca','Almeidas',25736,'Sesquilé'],
    ['Cundinamarca','Almeidas',25772,'Suesca'],
    ['Cundinamarca','Almeidas',25807,'Tibirita'],
    ['Cundinamarca','Almeidas',25873,'Villapinzón'],
    ['Cundinamarca','Alto Magdalena',25001,'Agua De Dios'],
    ['Cundinamarca','Alto Magdalena',25307,'Girardot'],
    ['Cundinamarca','Alto Magdalena',25324,'Guataquí'],
    ['Cundinamarca','Alto Magdalena',25368,'Jerusalén'],
    ['Cundinamarca','Alto Magdalena',25483,'Nariño'],
    ['Cundinamarca','Alto Magdalena',25488,'Nilo'],
    ['Cundinamarca','Alto Magdalena',25612,'Ricaurte'],
    ['Cundinamarca','Alto Magdalena',25815,'Tocaima'],
    ['Cundinamarca','Bajo Magdalena',25148,'Caparrapí'],
    ['Cundinamarca','Bajo Magdalena',25320,'Guaduas'],
    ['Cundinamarca','Bajo Magdalena',25572,'Puerto Salgar'],
    ['Cundinamarca','Gualiva',25019,'Albán'],
    ['Cundinamarca','Gualiva',25398,'La Peña'],
    ['Cundinamarca','Gualiva',25402,'La Vega'],
    ['Cundinamarca','Gualiva',25489,'Nimaima'],
    ['Cundinamarca','Gualiva',25491,'Nocaima'],
    ['Cundinamarca','Gualiva',25592,'Quebradanegra'],
    ['Cundinamarca','Gualiva',25658,'San Francisco'],
    ['Cundinamarca','Gualiva',25718,'Sasaima'],
    ['Cundinamarca','Gualiva',25777,'Supatá'],
    ['Cundinamarca','Gualiva',25851,'Útica'],
    ['Cundinamarca','Gualiva',25862,'Vergara'],
    ['Cundinamarca','Gualiva',25875,'Villeta'],
    ['Cundinamarca','Guavio',25293,'Gachala'],
    ['Cundinamarca','Guavio',25297,'Gacheta'],
    ['Cundinamarca','Guavio',25299,'Gama'],
    ['Cundinamarca','Guavio',25322,'Guasca'],
    ['Cundinamarca','Guavio',25326,'Guatavita'],
    ['Cundinamarca','Guavio',25372,'Junín'],
    ['Cundinamarca','Guavio',25377,'La Calera'],
    ['Cundinamarca','Guavio',25839,'Ubalá'],
    ['Cundinamarca','Magdalena Centro',25086,'Beltrán'],
    ['Cundinamarca','Magdalena Centro',25095,'Bituima'],
    ['Cundinamarca','Magdalena Centro',25168,'Chaguaní'],
    ['Cundinamarca','Magdalena Centro',25328,'Guayabal De Siquima'],
    ['Cundinamarca','Magdalena Centro',25580,'Puli'],
    ['Cundinamarca','Magdalena Centro',25662,'San Juan De Río Seco'],
    ['Cundinamarca','Magdalena Centro',25867,'Vianí'],
    ['Cundinamarca','Medina',25438,'Medina'],
    ['Cundinamarca','Medina',25530,'Paratebueno'],
    ['Cundinamarca','Oriente',25151,'Caqueza'],
    ['Cundinamarca','Oriente',25178,'Chipaque'],
    ['Cundinamarca','Oriente',25181,'Choachí'],
    ['Cundinamarca','Oriente',25279,'Fomeque'],
    ['Cundinamarca','Oriente',25281,'Fosca'],
    ['Cundinamarca','Oriente',25335,'Guayabetal'],
    ['Cundinamarca','Oriente',25339,'Gutiérrez'],
    ['Cundinamarca','Oriente',25594,'Quetame'],
    ['Cundinamarca','Oriente',25841,'Ubaque'],
    ['Cundinamarca','Oriente',25845,'Une'],
    ['Cundinamarca','Río Negro',25258,'El Peñón'],
    ['Cundinamarca','Río Negro',25394,'La Palma'],
    ['Cundinamarca','Río Negro',25513,'Pacho'],
    ['Cundinamarca','Río Negro',25518,'Paime'],
    ['Cundinamarca','Río Negro',25653,'San Cayetano'],
    ['Cundinamarca','Río Negro',25823,'Topaipi'],
    ['Cundinamarca','Río Negro',25871,'Villagomez'],
    ['Cundinamarca','Río Negro',25885,'Yacopí'],
    ['Cundinamarca','Sabana Centro',25126,'Cajicá'],
    ['Cundinamarca','Sabana Centro',25175,'Chía'],
    ['Cundinamarca','Sabana Centro',25200,'Cogua'],
    ['Cundinamarca','Sabana Centro',25295,'Gachancipá'],
    ['Cundinamarca','Sabana Centro',25486,'Nemocon'],
    ['Cundinamarca','Sabana Centro',25758,'Sopó'],
    ['Cundinamarca','Sabana Centro',25785,'Tabio'],
    ['Cundinamarca','Sabana Centro',25817,'Tocancipá'],
    ['Cundinamarca','Sabana Centro',25899,'Zipaquirá'],
    ['Cundinamarca','Sabana Occidente',25099,'Bojacá'],
    ['Cundinamarca','Sabana Occidente',25214,'Cota'],
    ['Cundinamarca','Sabana Occidente',25260,'El Rosal'],
    ['Cundinamarca','Sabana Occidente',25269,'Facatativá'],
    ['Cundinamarca','Sabana Occidente',25286,'Funza'],
    ['Cundinamarca','Sabana Occidente',25430,'Madrid'],
    ['Cundinamarca','Sabana Occidente',25473,'Mosquera'],
    ['Cundinamarca','Sabana Occidente',25769,'Subachoque'],
    ['Cundinamarca','Sabana Occidente',25799,'Tenjo'],
    ['Cundinamarca','Sabana Occidente',25898,'Zipacon'],
    ['Cundinamarca','Soacha',25740,'Sibaté'],
    ['Cundinamarca','Soacha',25754,'Soacha'],
    ['Cundinamarca','Sumapaz',25053,'Arbeláez'],
    ['Cundinamarca','Sumapaz',25120,'Cabrera'],
    ['Cundinamarca','Sumapaz',25290,'Fusagasugá'],
    ['Cundinamarca','Sumapaz',25312,'Granada'],
    ['Cundinamarca','Sumapaz',25524,'Pandi'],
    ['Cundinamarca','Sumapaz',25535,'Pasca'],
    ['Cundinamarca','Sumapaz',25649,'San Bernardo'],
    ['Cundinamarca','Sumapaz',25743,'Silvania'],
    ['Cundinamarca','Sumapaz',25805,'Tibacuy'],
    ['Cundinamarca','Sumapaz',25506,'Venecia'],
    ['Cundinamarca','Tequendama',25035,'Anapoima'],
    ['Cundinamarca','Tequendama',25040,'Anolaima'],
    ['Cundinamarca','Tequendama',25599,'Apulo'],
    ['Cundinamarca','Tequendama',25123,'Cachipay'],
    ['Cundinamarca','Tequendama',25245,'El Colegio'],
    ['Cundinamarca','Tequendama',25386,'La Mesa'],
    ['Cundinamarca','Tequendama',25596,'Quipile'],
    ['Cundinamarca','Tequendama',25645,'San Antonio De Tequendama'],
    ['Cundinamarca','Tequendama',25797,'Tena'],
    ['Cundinamarca','Tequendama',25878,'Viotá'],
    ['Cundinamarca','Ubate',25154,'Carmen De Carupa'],
    ['Cundinamarca','Ubate',25224,'Cucunubá'],
    ['Cundinamarca','Ubate',25288,'Fúquene'],
    ['Cundinamarca','Ubate',25317,'Guachetá'],
    ['Cundinamarca','Ubate',25407,'Lenguazaque'],
    ['Cundinamarca','Ubate',25745,'Simijaca'],
    ['Cundinamarca','Ubate',25779,'Susa'],
    ['Cundinamarca','Ubate',25781,'Sutatausa'],
    ['Cundinamarca','Ubate',25793,'Tausa'],
    ['Cundinamarca','Ubate',25843,'Ubate'],
    ['Guainia','Guainia',94343,'Barranco Mina'],
    ['Guainia','Guainia',94886,'Cacahual'],
    ['Guainia','Guainia',94001,'Inírida'],
    ['Guainia','Guainia',94885,'La Guadalupe'],
    ['Guainia','Guainia',94663,'Mapiripan'],
    ['Guainia','Guainia',94888,'Morichal'],
    ['Guainia','Guainia',94887,'Pana Pana'],
    ['Guainia','Guainia',94884,'Puerto Colombia'],
    ['Guainia','Guainia',94883,'San Felipe'],
    ['Guaviare','Guaviare',95015,'Calamar'],
    ['Guaviare','Guaviare',95025,'El Retorno'],
    ['Guaviare','Guaviare',95200,'Miraflores'],
    ['Guaviare','Guaviare',95001,'San José Del Guaviare'],
    ['Huila','Centro',41013,'Agrado'],
    ['Huila','Centro',41026,'Altamira'],
    ['Huila','Centro',41298,'Garzón'],
    ['Huila','Centro',41306,'Gigante'],
    ['Huila','Centro',41319,'Guadalupe'],
    ['Huila','Centro',41548,'Pital'],
    ['Huila','Centro',41770,'Suaza'],
    ['Huila','Centro',41791,'Tarqui'],
    ['Huila','Norte',41016,'Aipe'],
    ['Huila','Norte',41020,'Algeciras'],
    ['Huila','Norte',41078,'Baraya'],
    ['Huila','Norte',41132,'Campoalegre'],
    ['Huila','Norte',41206,'Colombia'],
    ['Huila','Norte',41349,'Hobo'],
    ['Huila','Norte',41357,'Iquira'],
    ['Huila','Norte',41001,'Neiva'],
    ['Huila','Norte',41524,'Palermo'],
    ['Huila','Norte',41615,'Rivera'],
    ['Huila','Norte',41676,'Santa María'],
    ['Huila','Norte',41799,'Tello'],
    ['Huila','Norte',41801,'Teruel'],
    ['Huila','Norte',41872,'Villavieja'],
    ['Huila','Norte',41885,'Yaguará'],
    ['Huila','Occidente',41378,'La Argentina'],
    ['Huila','Occidente',41396,'La Plata'],
    ['Huila','Occidente',41483,'Nátaga'],
    ['Huila','Occidente',41518,'Paicol'],
    ['Huila','Occidente',41797,'Tesalia'],
    ['Huila','Sur',41006,'Acevedo'],
    ['Huila','Sur',41244,'Elías'],
    ['Huila','Sur',41359,'Isnos'],
    ['Huila','Sur',41503,'Oporapa'],
    ['Huila','Sur',41530,'Palestina'],
    ['Huila','Sur',41551,'Pitalito'],
    ['Huila','Sur',41660,'Saladoblanco'],
    ['Huila','Sur',41668,'San Agustín'],
    ['Huila','Sur',41807,'Timaná'],
    ['La Guajira','Norte',44035,'Albania'],
    ['La Guajira','Norte',44090,'Dibulla'],
    ['La Guajira','Norte',44430,'Maicao'],
    ['La Guajira','Norte',44560,'Manaure'],
    ['La Guajira','Norte',44001,'Riohacha'],
    ['La Guajira','Norte',44847,'Uribia'],
    ['La Guajira','Sur',44078,'Barrancas'],
    ['La Guajira','Sur',44098,'Distraccion'],
    ['La Guajira','Sur',44110,'El Molino'],
    ['La Guajira','Sur',44279,'Fonseca'],
    ['La Guajira','Sur',44378,'Hatonuevo'],
    ['La Guajira','Sur',44420,'La Jagua Del Pilar'],
    ['La Guajira','Sur',44650,'San Juan Del Cesar'],
    ['La Guajira','Sur',44855,'Urumita'],
    ['La Guajira','Sur',44874,'Villanueva'],
    ['Magdalena','Centro',47058,'Ariguaní'],
    ['Magdalena','Centro',47170,'Chibolo'],
    ['Magdalena','Centro',47460,'Nueva Granada'],
    ['Magdalena','Centro',47555,'Plato'],
    ['Magdalena','Centro',47660,'Sabanas De San Angel'],
    ['Magdalena','Centro',47798,'Tenerife'],
    ['Magdalena','Norte',47030,'Algarrobo'],
    ['Magdalena','Norte',47053,'Aracataca'],
    ['Magdalena','Norte',47189,'Ciénaga'],
    ['Magdalena','Norte',47268,'El Reten'],
    ['Magdalena','Norte',47288,'Fundacion'],
    ['Magdalena','Norte',47570,'Pueblo Viejo'],
    ['Magdalena','Norte',47980,'Zona Bananera'],
    ['Magdalena','Río',47161,'Cerro San Antonio'],
    ['Magdalena','Río',47205,'Concordia'],
    ['Magdalena','Río',47258,'El Piñon'],
    ['Magdalena','Río',47541,'Pedraza'],
    ['Magdalena','Río',47551,'Pivijay'],
    ['Magdalena','Río',47605,'Remolino'],
    ['Magdalena','Río',47675,'Salamina'],
    ['Magdalena','Río',47745,'Sitionuevo'],
    ['Magdalena','Río',47960,'Zapayan'],
    ['Magdalena','Santa Marta',47001,'Santa Marta'],
    ['Magdalena','Sur',47245,'El Banco'],
    ['Magdalena','Sur',47318,'Guamal'],
    ['Magdalena','Sur',47545,'Pijiño Del Carmen'],
    ['Magdalena','Sur',47692,'San Sebastian De Buenavista'],
    ['Magdalena','Sur',47703,'San Zenon'],
    ['Magdalena','Sur',47707,'Santa Ana'],
    ['Magdalena','Sur',47720,'Santa Barbara De Pinto'],
    ['Meta','Ariari',50251,'El Castillo'],
    ['Meta','Ariari',50270,'El Dorado'],
    ['Meta','Ariari',50287,'Fuente De Oro'],
    ['Meta','Ariari',50313,'Granada'],
    ['Meta','Ariari',50350,'La Macarena'],
    ['Meta','Ariari',50370,'La Uribe'],
    ['Meta','Ariari',50400,'Lejanías'],
    ['Meta','Ariari',50325,'Mapiripan'],
    ['Meta','Ariari',50330,'Mesetas'],
    ['Meta','Ariari',50450,'Puerto Concordia'],
    ['Meta','Ariari',50577,'Puerto Lleras'],
    ['Meta','Ariari',50590,'Puerto Rico'],
    ['Meta','Ariari',50683,'San Juan De Arama'],
    ['Meta','Ariari',50711,'Vista Hermosa'],
    ['Meta','Capital',50001,'Villavicencio'],
    ['Meta','Piedemonte',50006,'Acacias'],
    ['Meta','Piedemonte',50110,'Barranca De Upia'],
    ['Meta','Piedemonte',50150,'Castilla La Nueva'],
    ['Meta','Piedemonte',50226,'Cumaral'],
    ['Meta','Piedemonte',50245,'El Calvario'],
    ['Meta','Piedemonte',50318,'Guamal'],
    ['Meta','Piedemonte',50606,'Restrepo'],
    ['Meta','Piedemonte',50680,'San Carlos Guaroa'],
    ['Meta','Piedemonte',50686,'San Juanito'],
    ['Meta','Piedemonte',50223,'San Luis De Cubarral'],
    ['Meta','Piedemonte',50689,'San Martín'],
    ['Meta','Río Meta',50124,'Cabuyaro'],
    ['Meta','Río Meta',50568,'Puerto Gaitán'],
    ['Meta','Río Meta',50573,'Puerto Lopez'],
    ['Nariño','Centro',52240,'Chachagui'],
    ['Nariño','Centro',52207,'Consaca'],
    ['Nariño','Centro',52254,'El Peñol'],
    ['Nariño','Centro',52260,'El Tambo'],
    ['Nariño','Centro',52381,'La Florida'],
    ['Nariño','Centro',52480,'Nariño'],
    ['Nariño','Centro',52001,'Pasto'],
    ['Nariño','Centro',52683,'Sandoná'],
    ['Nariño','Centro',52788,'Tangua'],
    ['Nariño','Centro',52885,'Yacuanquer'],
    ['Nariño','Centro Occidente',52036,'Ancuya'],
    ['Nariño','Centro Occidente',52320,'Guaitarilla'],
    ['Nariño','Centro Occidente',52385,'La Llanada'],
    ['Nariño','Centro Occidente',52411,'Linares'],
    ['Nariño','Centro Occidente',52418,'Los Andes'],
    ['Nariño','Centro Occidente',52435,'Mallama'],
    ['Nariño','Centro Occidente',52506,'Ospina'],
    ['Nariño','Centro Occidente',52565,'Providencia'],
    ['Nariño','Centro Occidente',52612,'Ricaurte'],
    ['Nariño','Centro Occidente',52678,'Samaniego'],
    ['Nariño','Centro Occidente',52699,'Santa Cruz'],
    ['Nariño','Centro Occidente',52720,'Sapuyes'],
    ['Nariño','Centro Occidente',52838,'Tuquerres'],
    ['Nariño','Costa',52079,'Barbacoas'],
    ['Nariño','Costa',52250,'El Charco'],
    ['Nariño','Costa',52520,'Francisco Pizarro'],
    ['Nariño','Costa',52390,'La Tola'],
    ['Nariño','Costa',52427,'Magui'],
    ['Nariño','Costa',52473,'Mosquera'],
    ['Nariño','Costa',52490,'Olaya Herrera'],
    ['Nariño','Costa',52621,'Roberto Payan'],
    ['Nariño','Costa',52696,'Santa Barbara'],
    ['Nariño','Costa',52835,'Tumaco'],
    ['Nariño','Norte',52019,'Alban'],
    ['Nariño','Norte',52051,'Arboleda'],
    ['Nariño','Norte',52083,'Belen'],
    ['Nariño','Norte',52110,'Buesaco'],
    ['Nariño','Norte',52203,'Colon'],
    ['Nariño','Norte',52233,'Cumbitara'],
    ['Nariño','Norte',52256,'El Rosario'],
    ['Nariño','Norte',52258,'El Tablon De Gomez'],
    ['Nariño','Norte',52378,'La Cruz'],
    ['Nariño','Norte',52399,'La Union'],
    ['Nariño','Norte',52405,'Leiva'],
    ['Nariño','Norte',52540,'Policarpa'],
    ['Nariño','Norte',52685,'San Bernardo'],
    ['Nariño','Norte',52687,'San Lorenzo'],
    ['Nariño','Norte',52693,'San Pablo'],
    ['Nariño','Norte',52694,'San Pedro De Cartago'],
    ['Nariño','Norte',52786,'Taminango'],
    ['Nariño','Sur',52022,'Aldana'],
    ['Nariño','Sur',52210,'Contadero'],
    ['Nariño','Sur',52215,'Córdoba'],
    ['Nariño','Sur',52224,'Cuaspud'],
    ['Nariño','Sur',52227,'Cumbal'],
    ['Nariño','Sur',52287,'Funes'],
    ['Nariño','Sur',52317,'Guachucal'],
    ['Nariño','Sur',52323,'Gualmatan'],
    ['Nariño','Sur',52352,'Iles'],
    ['Nariño','Sur',52354,'Imues'],
    ['Nariño','Sur',52356,'Ipiales'],
    ['Nariño','Sur',52560,'Potosí'],
    ['Nariño','Sur',52573,'Puerres'],
    ['Nariño','Sur',52585,'Pupiales'],
    ['Norte de Santander','Centro',54051,'Arboledas'],
    ['Norte de Santander','Centro',54223,'Cucutilla'],
    ['Norte de Santander','Centro',54313,'Gramalote'],
    ['Norte de Santander','Centro',54418,'Lourdes'],
    ['Norte de Santander','Centro',54660,'Salazar'],
    ['Norte de Santander','Centro',54680,'Santiago'],
    ['Norte de Santander','Centro',54871,'Villa Caro'],
    ['Norte de Santander','Norte',54109,'Bucarasica'],
    ['Norte de Santander','Norte',54250,'El Tarra'],
    ['Norte de Santander','Norte',54720,'Sardinata'],
    ['Norte de Santander','Norte',54810,'Tibú'],
    ['Norte de Santander','Occidente',54003,'Abrego'],
    ['Norte de Santander','Occidente',54128,'Cachirá'],
    ['Norte de Santander','Occidente',54206,'Convención'],
    ['Norte de Santander','Occidente',54245,'El Carmen'],
    ['Norte de Santander','Occidente',54344,'Hacarí'],
    ['Norte de Santander','Occidente',54385,'La Esperanza'],
    ['Norte de Santander','Occidente',54398,'La Playa'],
    ['Norte de Santander','Occidente',54498,'Ocaña'],
    ['Norte de Santander','Occidente',54670,'San Calixto'],
    ['Norte de Santander','Occidente',54800,'Teorama'],
    ['Norte de Santander','Oriental',54001,'Cúcuta'],
    ['Norte de Santander','Oriental',54261,'El Zulia'],
    ['Norte de Santander','Oriental',54405,'Los Patios'],
    ['Norte de Santander','Oriental',54553,'Puerto Santander'],
    ['Norte de Santander','Oriental',54673,'San Cayetano'],
    ['Norte de Santander','Oriental',54874,'Villa Del Rosario'],
    ['Norte de Santander','Sur Occidente',54125,'Cácota'],
    ['Norte de Santander','Sur Occidente',54174,'Chitagá'],
    ['Norte de Santander','Sur Occidente',54480,'Mutiscua'],
    ['Norte de Santander','Sur Occidente',54518,'Pamplona'],
    ['Norte de Santander','Sur Occidente',54520,'Pamplonita'],
    ['Norte de Santander','Sur Occidente',54743,'Silos'],
    ['Norte de Santander','Sur Oriente',54099,'Bochalema'],
    ['Norte de Santander','Sur Oriente',54172,'Chinácota'],
    ['Norte de Santander','Sur Oriente',54239,'Durania'],
    ['Norte de Santander','Sur Oriente',54347,'Herrán'],
    ['Norte de Santander','Sur Oriente',54377,'Labateca'],
    ['Norte de Santander','Sur Oriente',54599,'Ragonvalia'],
    ['Norte de Santander','Sur Oriente',54820,'Toledo'],
    ['Putumayo','Putumayo',86219,'Colón'],
    ['Putumayo','Putumayo',86001,'Mocoa'],
    ['Putumayo','Putumayo',86320,'Orito'],
    ['Putumayo','Putumayo',86568,'Puerto Asis'],
    ['Putumayo','Putumayo',86569,'Puerto Caicedo'],
    ['Putumayo','Putumayo',86571,'Puerto Guzman'],
    ['Putumayo','Putumayo',86573,'Puerto Leguizamo'],
    ['Putumayo','Putumayo',86755,'San Francisco'],
    ['Putumayo','Putumayo',86757,'San Miguel'],
    ['Putumayo','Putumayo',86760,'Santiago'],
    ['Putumayo','Putumayo',86749,'Sibundoy'],
    ['Putumayo','Putumayo',86865,'Valle Del Guamuez'],
    ['Putumayo','Putumayo',86885,'Villa Garzon'],
    ['Quindio','Capital',63001,'Armenia'],
    ['Quindio','Capital',63111,'Buenavista'],
    ['Quindio','Capital',63130,'Calarca'],
    ['Quindio','Cordilléranos',63212,'Cordoba'],
    ['Quindio','Cordilléranos',63302,'Genova'],
    ['Quindio','Cordilléranos',63548,'Pijao'],
    ['Quindio','Fría',63272,'Filandia'],
    ['Quindio','Fría',63690,'Salento'],
    ['Quindio','Norte',63190,'Circasia'],
    ['Quindio','Valle',63401,'La Tebaida'],
    ['Quindio','Valle',63470,'Montengro'],
    ['Quindio','Valle',63594,'Quimbaya'],
    ['Risaralda','Uno – Vertiente Oriental',66170,'Dosquebradas'],
    ['Risaralda','Uno – Vertiente Oriental',66400,'La Virginia'],
    ['Risaralda','Uno – Vertiente Oriental',66440,'Marsella'],
    ['Risaralda','Uno – Vertiente Oriental',66001,'Pereira'],
    ['Risaralda','Uno – Vertiente Oriental',66682,'Santa Rosa De Cabal'],
    ['Risaralda','Dos – Vertiente Occidental',66045,'Apía'],
    ['Risaralda','Dos – Vertiente Occidental',66075,'Balboa'],
    ['Risaralda','Dos – Vertiente Occidental',66088,'Belén De Umbría'],
    ['Risaralda','Dos – Vertiente Occidental',66318,'Guática'],
    ['Risaralda','Dos – Vertiente Occidental',66383,'La Celia'],
    ['Risaralda','Dos – Vertiente Occidental',66594,'Quinchia'],
    ['Risaralda','Dos – Vertiente Occidental',66687,'Santuario'],
    ['Risaralda','Tres – Vertiente del Pacífico',66456,'Mistrató'],
    ['Risaralda','Tres – Vertiente del Pacífico',66572,'Pueblo Rico'],
    ['Santander','Comunera',68176,'Chima'],
    ['Santander','Comunera',68209,'Confines'],
    ['Santander','Comunera',68211,'Contratación'],
    ['Santander','Comunera',68245,'El Guacamayo'],
    ['Santander','Comunera',68296,'Galán'],
    ['Santander','Comunera',68298,'Gambita'],
    ['Santander','Comunera',68320,'Guadalupe'],
    ['Santander','Comunera',68322,'Guapotá'],
    ['Santander','Comunera',68344,'Hato'],
    ['Santander','Comunera',68500,'Oiba'],
    ['Santander','Comunera',68522,'Palmar'],
    ['Santander','Comunera',68524,'Palmas Del Socorro'],
    ['Santander','Comunera',68720,'Santa Helena Del Opón'],
    ['Santander','Comunera',68745,'Simacota'],
    ['Santander','Comunera',68755,'Socorro'],
    ['Santander','Comunera',68770,'Suaita'],
    ['Santander','García Rovira',68147,'Capitanejo'],
    ['Santander','García Rovira',68152,'Carcasí'],
    ['Santander','García Rovira',68160,'Cepitá'],
    ['Santander','García Rovira',68162,'Cerrito'],
    ['Santander','García Rovira',68207,'Concepción'],
    ['Santander','García Rovira',68266,'Enciso'],
    ['Santander','García Rovira',68318,'Guaca'],
    ['Santander','García Rovira',68425,'Macaravita'],
    ['Santander','García Rovira',68432,'Málaga'],
    ['Santander','García Rovira',68468,'Molagavita'],
    ['Santander','García Rovira',68669,'San Andrés'],
    ['Santander','García Rovira',68684,'San José De Miranda'],
    ['Santander','García Rovira',68686,'San Miguel'],
    ['Santander','Guanenta',68051,'Aratoca'],
    ['Santander','Guanenta',68079,'Barichara'],
    ['Santander','Guanenta',68121,'Cabrera'],
    ['Santander','Guanenta',68167,'Charalá'],
    ['Santander','Guanenta',68217,'Coromoro'],
    ['Santander','Guanenta',68229,'Curití'],
    ['Santander','Guanenta',68264,'Encino'],
    ['Santander','Guanenta',68370,'Jordán'],
    ['Santander','Guanenta',68464,'Mogotes'],
    ['Santander','Guanenta',68498,'Ocamonte'],
    ['Santander','Guanenta',68502,'Onzaga'],
    ['Santander','Guanenta',68533,'Páramo'],
    ['Santander','Guanenta',68549,'Pinchote'],
    ['Santander','Guanenta',68679,'San Gil'],
    ['Santander','Guanenta',68682,'San Joaquín'],
    ['Santander','Guanenta',68855,'Valle De San José'],
    ['Santander','Guanenta',68872,'Villanueva'],
    ['Santander','Mares',68081,'Barrancabermeja'],
    ['Santander','Mares',68092,'Betulia'],
    ['Santander','Mares',68235,'El Carmen De Chucurí'],
    ['Santander','Mares',68575,'Puerto Wilches'],
    ['Santander','Mares',68655,'Sabana De Torres'],
    ['Santander','Mares',68689,'San Vicente De Chucurí'],
    ['Santander','Mares',68895,'Zapatoca'],
    ['Santander','Soto',68001,'Bucaramanga'],
    ['Santander','Soto',68132,'California'],
    ['Santander','Soto',68169,'Charta'],
    ['Santander','Soto',68255,'El Playón'],
    ['Santander','Soto',68276,'Floridablanca'],
    ['Santander','Soto',68307,'Girón'],
    ['Santander','Soto',68406,'Lebríja'],
    ['Santander','Soto',68418,'Los Santos'],
    ['Santander','Soto',68444,'Matanza'],
    ['Santander','Soto',68547,'Piedecuesta'],
    ['Santander','Soto',68615,'Rionegro'],
    ['Santander','Soto',68705,'Santa Bárbara'],
    ['Santander','Soto',68780,'Surata'],
    ['Santander','Soto',68820,'Tona'],
    ['Santander','Soto',68867,'Vetas'],
    ['Santander','Vélez',68013,'Aguada'],
    ['Santander','Vélez',68020,'Albania'],
    ['Santander','Vélez',68077,'Barbosa'],
    ['Santander','Vélez',68101,'Bolívar'],
    ['Santander','Vélez',68179,'Chipatá'],
    ['Santander','Vélez',68190,'Cimitarra'],
    ['Santander','Vélez',68250,'El Peñón'],
    ['Santander','Vélez',68271,'Florián'],
    ['Santander','Vélez',68324,'Guavatá'],
    ['Santander','Vélez',68327,'Guepsa'],
    ['Santander','Vélez',68368,'Jesús María'],
    ['Santander','Vélez',68377,'La Belleza'],
    ['Santander','Vélez',68397,'La Paz'],
    ['Santander','Vélez',68385,'Landázuri'],
    ['Santander','Vélez',68572,'Puente Nacional'],
    ['Santander','Vélez',68573,'Puerto Parra'],
    ['Santander','Vélez',68673,'San Benito'],
    ['Santander','Vélez',68773,'Sucre'],
    ['Santander','Vélez',68861,'Vélez'],
    ['Sucre','Mojana',70265,'Guaranda'],
    ['Sucre','Mojana',70429,'Majagual'],
    ['Sucre','Mojana',70771,'Sucre'],
    ['Sucre','Montes de María',70230,'Chalán'],
    ['Sucre','Montes de María',70204,'Coloso'],
    ['Sucre','Montes de María',70473,'Morroa'],
    ['Sucre','Montes de María',70508,'Ovejas'],
    ['Sucre','Montes de María',70001,'Sincelejo'],
    ['Sucre','Morroso Uillo',70221,'Coveñas'],
    ['Sucre','Morroso Uillo',70523,'Palmito'],
    ['Sucre','Morroso Uillo',70713,'San Onofre'],
    ['Sucre','Morroso Uillo',70820,'Santiago De Tolú'],
    ['Sucre','Morroso Uillo',70823,'Tolú Viejo'],
    ['Sucre','Sabanas',70110,'Buenavista'],
    ['Sucre','Sabanas',70215,'Corozal'],
    ['Sucre','Sabanas',70233,'El Roble'],
    ['Sucre','Sabanas',70235,'Galeras'],
    ['Sucre','Sabanas',70418,'Los Palmitos'],
    ['Sucre','Sabanas',70670,'Sampués'],
    ['Sucre','Sabanas',70702,'San Juan Betulia'],
    ['Sucre','Sabanas',70717,'San Pedro'],
    ['Sucre','Sabanas',70742,'Sincé'],
    ['Sucre','San Jorge',70124,'Caimito'],
    ['Sucre','San Jorge',70400,'La Unión'],
    ['Sucre','San Jorge',70678,'San Benito Abad'],
    ['Sucre','San Jorge',70708,'San Marcos'],
    ['Tolima','Norte',73030,'Ambalema'],
    ['Tolima','Norte',73055,'Armero'],
    ['Tolima','Norte',73270,'Falan'],
    ['Tolima','Norte',73283,'Fresno'],
    ['Tolima','Norte',73349,'Honda'],
    ['Tolima','Norte',73443,'Mariquita'],
    ['Tolima','Norte',73520,'Palocabildo'],
    ['Tolima','Oriente',73148,'Carmen De Apicalá'],
    ['Tolima','Oriente',73226,'Cunday'],
    ['Tolima','Oriente',73352,'Icononzo'],
    ['Tolima','Oriente',73449,'Melgar'],
    ['Tolima','Oriente',73873,'Villarrica'],
    ['Tolima','Sur',73067,'Ataco'],
    ['Tolima','Sur',73168,'Chaparral'],
    ['Tolima','Sur',73217,'Coyaima'],
    ['Tolima','Sur',73483,'Natagaima'],
    ['Tolima','Sur',73504,'Ortega'],
    ['Tolima','Sur',73555,'Planadas'],
    ['Tolima','Sur',73616,'Rioblanco'],
    ['Tolima','Sur',73622,'Roncesvalles'],
    ['Tolima','Sur',73675,'San Antonio'],
    ['Tolima','Ibague',73026,'Alvarado'],
    ['Tolima','Ibague',73043,'Anzoátegui'],
    ['Tolima','Ibague',73124,'Cajamarca'],
    ['Tolima','Ibague',73200,'Coello'],
    ['Tolima','Ibague',73268,'Espinal'],
    ['Tolima','Ibague',73275,'Flandes'],
    ['Tolima','Ibague',73001,'Ibague'],
    ['Tolima','Ibague',73547,'Piedras'],
    ['Tolima','Ibague',73624,'Rovira'],
    ['Tolima','Ibague',73678,'San Luis'],
    ['Tolima','Ibague',73854,'Valle De San Juan'],
    ['Tolima','Suroriente',73024,'Alpujarra'],
    ['Tolima','Suroriente',73236,'Dolores'],
    ['Tolima','Suroriente',73319,'Guamo'],
    ['Tolima','Suroriente',73563,'Prado'],
    ['Tolima','Suroriente',73585,'Purificación'],
    ['Tolima','Suroriente',73671,'Saldaña'],
    ['Tolima','Suroriente',73770,'Suárez'],
    ['Tolima','Nevados',73152,'Casabianca'],
    ['Tolima','Nevados',73347,'Herveo'],
    ['Tolima','Nevados',73408,'Lerida'],
    ['Tolima','Nevados',73411,'Libano'],
    ['Tolima','Nevados',73461,'Murillo'],
    ['Tolima','Nevados',73686,'Santa Isabel'],
    ['Tolima','Nevados',73861,'Venadillo'],
    ['Tolima','Nevados',73870,'Villahermosa'],
    ['Valle del Cauca','Centro',76036,'Andalucía'],
    ['Valle del Cauca','Centro',76111,'Buga'],
    ['Valle del Cauca','Centro',76113,'Bugalagrande'],
    ['Valle del Cauca','Centro',76126,'Calima'],
    ['Valle del Cauca','Centro',76248,'El Cerrito'],
    ['Valle del Cauca','Centro',76306,'Ginebra'],
    ['Valle del Cauca','Centro',76318,'Guacarí'],
    ['Valle del Cauca','Centro',76606,'Restrepo'],
    ['Valle del Cauca','Centro',76616,'Riofrio'],
    ['Valle del Cauca','Centro',76670,'San Pedro'],
    ['Valle del Cauca','Centro',76828,'Trujillo'],
    ['Valle del Cauca','Centro',76834,'Tuluá'],
    ['Valle del Cauca','Centro',76890,'Yotoco'],
    ['Valle del Cauca','Norte',76020,'Alcala'],
    ['Valle del Cauca','Norte',76041,'Ansermanuevo'],
    ['Valle del Cauca','Norte',76054,'Argelia'],
    ['Valle del Cauca','Norte',76100,'Bolívar'],
    ['Valle del Cauca','Norte',76147,'Cartago'],
    ['Valle del Cauca','Norte',76243,'El Águila'],
    ['Valle del Cauca','Norte',76246,'El Cairo'],
    ['Valle del Cauca','Norte',76250,'El Dovio'],
    ['Valle del Cauca','Norte',76400,'La Unión'],
    ['Valle del Cauca','Norte',76403,'La Victoria'],
    ['Valle del Cauca','Norte',76497,'Obando'],
    ['Valle del Cauca','Norte',76622,'Roldanillo'],
    ['Valle del Cauca','Norte',76823,'Toro'],
    ['Valle del Cauca','Norte',76845,'Ulloa'],
    ['Valle del Cauca','Norte',76863,'Versalles'],
    ['Valle del Cauca','Norte',76895,'Zarzal'],
    ['Valle del Cauca','Occidente',76109,'Buenaventura'],
    ['Valle del Cauca','Oriente',76122,'Caicedonia'],
    ['Valle del Cauca','Oriente',76736,'Sevilla'],
    ['Valle del Cauca','Sur',76001,'Cali'],
    ['Valle del Cauca','Sur',76130,'Candelaria'],
    ['Valle del Cauca','Sur',76233,'Dagua'],
    ['Valle del Cauca','Sur',76275,'Florida'],
    ['Valle del Cauca','Sur',76364,'Jamundí'],
    ['Valle del Cauca','Sur',76377,'La Cumbre'],
    ['Valle del Cauca','Sur',76520,'Palmira'],
    ['Valle del Cauca','Sur',76563,'Pradera'],
    ['Valle del Cauca','Sur',76869,'Vijes'],
    ['Valle del Cauca','Sur',76892,'Yumbo'],
    ['Vaupes','Vaupes',97161,'Caruru'],
    ['Vaupes','Vaupes',97001,'Mitú'],
    ['Vaupes','Vaupes',97511,'Pacoa'],
    ['Vaupes','Vaupes',97777,'Papunahua'],
    ['Vaupes','Vaupes',97666,'Taraira'],
    ['Vaupes','Vaupes',97889,'Yavaraté'],
    ['Vichada','Vichada',99773,'Cumaribo'],
    ['Vichada','Vichada',99524,'La Primavera'],
    ['Vichada','Vichada',99001,'Puerto Carreño'],
    ['Vichada','Vichada',99624,'Santa Rosalía'],    
]

oc=PgConnection(connection)
po=PgOperations(pgConnection=oc, autoCommit=True, global_print_queries=False)
#snr_persona_titular_tipo

#oc.cursor.execute('create table codelist.municipio (gid serial primary key, departamento varchar, provincia varchar, codigo_municipio integer unique, nombre_municipio varchar, unique (codigo_municipio, nombre_municipio))')
#oc.commit()
#print ('Tabla municipios creada')

for v in ld:
    d={}
    d['departamento']=v[0]
    fv=FieldsAndValues(d=d)
    #print(fv.list_field_values)
    po.pgInsert(table_name='codelist.departamento', fieldsAndValues=fv, str_fields_returning=None, print_query=False) 
print ('Departamentos insertados')

for v in lp:
    d={}
    d['provincia']=v[0]
    fv=FieldsAndValues(d=d)
    po.pgInsert(table_name='codelist.provincia', fieldsAndValues=fv, str_fields_returning=None, print_query=False) 

print ('Provincias insertadas')

for v in lm:
    d={}
    d['departamento']=v[0]
    d['provincia']=v[1]
    d['codigo_municipio']=v[2]
    d['nombre_municipio']=v[3]
    fv=FieldsAndValues(d=d)
    po.pgInsert(table_name='codelist.municipio', fieldsAndValues=fv, str_fields_returning=None, print_query=False) 

print ('Municipios insertados')



