# Generated by Django 4.1 on 2023-12-18 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('departamento', models.CharField(max_length=100, unique=True)),
                ('provincia', models.CharField(max_length=100, unique=True)),
                ('codigo_municipio', models.IntegerField()),
                ('nombre_municipio', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'codelist"."municipio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SnrPersonaTitularTipo',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('snr_persona_titular_tipo', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'db_table': 'codelist"."snr_persona_titular_tipo',
                'managed': False,
            },
        ),
    ]
