# Generated by Django 4.1 on 2023-12-18 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcodelist', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('departamento', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'codelist"."municipio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('provincia', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'codelist"."municipio',
                'managed': False,
            },
        ),
    ]
