# Generated by Django 4.1 on 2023-12-19 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appcodelist', '0002_departamento_provincia'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='departamento',
            table='codelist"."departamento',
        ),
        migrations.AlterModelTable(
            name='provincia',
            table='codelist"."provincia',
        ),
    ]
