# Generated by Django 4.1 on 2024-01-07 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FicheroZip',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateTimeField(auto_now=True)),
                ('fecha_descarga', models.DateTimeField(blank=True)),
                ('nombre_fichero', models.FileField(upload_to='ficheros_zip')),
            ],
            options={
                'db_table': 'source"."fichero_zip',
                'managed': False,
            },
        ),
    ]
