# Generated by Django 4.2.7 on 2024-01-11 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivoZip',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateTimeField(auto_now=True)),
                ('fecha_descarga', models.DateTimeField(blank=True)),
                ('archivo', models.FileField(upload_to='ficheros_zip')),
            ],
            options={
                'db_table': 'source"."archivo_zip',
                'managed': False,
            },
        ),
    ]
